import Batteries

/-!
# Induction on the natural numbers

This module is a literate proof that doubles as a small scientific
note and a runnable Lean 4 mechanization. The narrative is written
in `/-! ... -/` module docstrings and `/-- ... -/` declaration
docstrings; the code between them is the mechanization. repo-docs
Theory pages render both: the prose flows like an article, the
declarations carry semantic tokens and hovers, and the proof state
follows the reader's cursor in the side panel.

The development is organised around the right-identity property of
addition,

$$
\forall n \in \mathbb{N},\quad n + 0 = n,
$$

a textbook starting point for studying induction. We will state the
theorem in §3, prove it by induction on $n$, and discuss what the
proof state looks like at each step. A few auxiliary functions in
§2 fix notation and exercise the rendering pipeline.

```mermaid
flowchart LR
  Source[Lean source] --> Verso[Verso literate data]
  Verso --> Fragment[Interactive Lean fragment]
  Fragment --> Docs[repo-docs page shell]
```

The induction principle on $\mathbb{N}$ that justifies the proof reads:

$$
\forall P : \mathbb{N} \to \mathsf{Prop},\quad
P(0) \,\land\, \bigl(\forall n,\; P(n) \to P(n+1)\bigr)
\;\to\; \forall n,\; P(n).
$$
-/

namespace Demo

/-!
## 1. Preliminaries

We work with Lean's built-in inductive type `Nat`, generated by the
constant $0$ and the successor function $\mathrm{succ}\, n = n + 1$.
The two trivial declarations below establish that equality on `Nat`
is reflexive and that `rfl` is enough to discharge it. They are
useful as warm-ups for the proof state panel: hover the proof term
on the right of `:=` to see the goal each declaration closes.
-/

theorem identity (value : Nat) : value = value := rfl

theorem identity_again (value : Nat) : value = value := identity value

/-!
### 1.1. Auxiliary functions

The next three definitions fix small bits of notation that recur in
the discussion. They have no proof obligations and exist purely so
the rendering pipeline has something concrete to attach docstrings,
hover popovers, and cross-references to.
-/

def overlay (left right : Nat) : Nat := left + right

/-- `cross left right` is a documented declaration used to check docstring attachment. -/
def cross (left right : Nat) : Nat := left * right

/-- Doubles a natural number. The result satisfies $\mathrm{double}(n) = 2n$
and, equivalently, $\mathrm{double}(n) = n + n$. Hover the identifier in
the proof of `add_zero_demo` below to see this docstring rendered with
inline math. -/
def double (n : Nat) : Nat := n + n

/-!
## 2. Right identity of addition

We now turn to the central result of the module. The claim is that
adding zero on the right is the identity operation:

$$
\forall n \in \mathbb{N},\quad n + 0 = n.
$$

The proof proceeds by induction on $n$, mirroring the schema given
in the introduction.

- **Base case.** When $n = 0$, the goal $0 + 0 = 0$ is closed by
  `rfl` because Lean's `Nat.add` is defined by structural recursion
  on its second argument and $\mathrm{Nat.add}\, 0 \, 0$ reduces to
  $0$ definitionally.
- **Successor case.** Assuming the inductive hypothesis $n + 0 = n$
  (named `ih` in the script below), we must show
  $\mathrm{succ}\, n + 0 = \mathrm{succ}\, n$. By the defining
  equation of `Nat.add`, the left-hand side reduces to
  $\mathrm{succ}\,(n + 0)$; applying $\mathrm{congrArg}$ with
  `Nat.succ` to `ih` yields the goal.

Hover any tactic in the proof to inspect the proof state at that
point — the right-hand panel will track your cursor and show the
hypotheses and conclusion that Lean's elaborator carries at that
step.
-/

theorem add_zero_demo (n : Nat) : n + 0 = n := by
  induction n with
  | zero =>
      rfl
  | succ n ih =>
      exact congrArg Nat.succ ih

/-!
## 3. Discussion

The mechanized proof and the prose above describe the same argument
at two levels of formality. The Lean term `congrArg Nat.succ ih` is
the operational counterpart of the natural-language statement
"applying $\mathrm{succ}$ to both sides of the inductive hypothesis
closes the successor case".

Two observations are worth recording.

1. The proof object produced by Lean is a closed term of type
   `n + 0 = n`. Its existence is what justifies the entry of
   `add_zero_demo` in the term language; subsequent declarations
   in this section, or in downstream modules, may invoke it as a
   lemma.
2. The interactive proof state is a *separate* artefact — it is
   meaningful only during elaboration. Verso captures it on each
   tactic boundary and repo-docs surfaces it in the side panel so
   the narrative and the mechanization can be read together,
   without the reader having to open the file in an editor.

A natural next step is to extend the development to the left
identity ($0 + n = n$), associativity, and commutativity. Each
follows the same induction-on-$n$ schema, with the same shape of
prose-and-mechanization interleaving.
-/

end Demo
