{inputs, ...}: {
  imports = [
    inputs.treefmt-nix.flakeModule
  ];

  perSystem = {
    config,
    pkgs,
    lib,
    ...
  }: let
    # Format + lint toolchain bundle.
    #
    # nixpkgs no longer ships individual node packages (the old
    # `nodePackages` set was retired), so we vendor a tiny
    # package.json under nix/format/ that pulls prettier +
    # prettier-plugin-astro + stylelint + its config peers. The
    # buildNpmPackage derivation produces self-contained wrappers we
    # register as custom treefmt programs.
    formatTools = pkgs.buildNpmPackage {
      pname = "repo-docs-format-tools";
      version = "1.0.0";
      src = ../format;
      # Computed once via `nix build .#... --print-build-logs` and
      # the resulting `got: sha256-...` line. Update on every
      # package-lock.json change.
      npmDepsHash = "sha256-eedRUl3ws5W3/KGqW5dKGHfKLmfBWDSoORdy6x3A5YI=";
      dontNpmBuild = true;
      installPhase = ''
        runHook preInstall
        mkdir -p $out/lib $out/bin
        cp -r node_modules $out/lib/node_modules
        cp -r package.json $out/lib/package.json
        cat > $out/bin/prettier <<EOF
        #!${pkgs.runtimeShell}
        exec ${pkgs.nodejs_22}/bin/node $out/lib/node_modules/prettier/bin/prettier.cjs \\
          --plugin=$out/lib/node_modules/prettier-plugin-astro/dist/index.js \\
          "\$@"
        EOF
        chmod +x $out/bin/prettier
        cat > $out/bin/stylelint <<EOF
        #!${pkgs.runtimeShell}
        # --config-basedir lets stylelint resolve the
        # `stylelint-config-standard` etc. extends entries against
        # the bundled node_modules tree rather than the consumer
        # repo's cwd, which doesn't carry those packages.
        exec ${pkgs.nodejs_22}/bin/node $out/lib/node_modules/stylelint/bin/stylelint.mjs \\
          --config-basedir=$out/lib/node_modules \\
          "\$@"
        EOF
        chmod +x $out/bin/stylelint
        runHook postInstall
      '';
    };
  in {
    treefmt = {
      projectRootFile = "flake.nix";

      programs = {
        # Nix files
        alejandra.enable = true;
      };

      # Custom prettier program. The `**/*.ext` glob form is what
      # treefmt's matcher actually filters on; bare `*.ext` falls
      # through and prettier gets handed every file in the run.
      #
      # `.astro` is back in the sweep now that the embed-with-script
      # patterns that broke prettier-plugin-astro 0.14.x have been
      # extracted into dedicated component files (TypstEmbed,
      # HaddockEmbed, ThemeInitScript). New components carrying
      # `<script is:inline>` blocks should follow the same pattern:
      # one component per embed, single-element conditional in the
      # caller — never `{cond && <section>...<script>}` inline.
      settings.formatter.prettier = {
        command = "${formatTools}/bin/prettier";
        options = ["--write"];
        includes = [
          "**/*.astro"
          "**/*.css"
          "**/*.html"
          "**/*.js"
          "**/*.json"
          "**/*.md"
          "**/*.mjs"
          "**/*.ts"
          "**/*.yaml"
          "**/*.yml"
        ];
      };

      # Stylelint sweeps the CSS files prettier already formatted to
      # enforce naming + cascade discipline (no hex outside theme
      # files, no rgb()/hsl() in favour of color-mix, BEM namespace
      # patterns). It runs after prettier inside the same `nix fmt`
      # pass; treefmt orders formatters by name so we prefix the
      # name with `z-` to put stylelint last.
      settings.formatter."z-stylelint" = {
        command = "${formatTools}/bin/stylelint";
        options = ["--fix"];
        includes = ["**/*.css"];
        excludes = [
          # Theme palette files own the literal hex values we want
          # to enforce against everywhere else, so they're allowed
          # to break the no-hex rule. The css-code-style skill's
          # checklist covers cross-file consistency for these.
          "template/src/styles/themes/*.css"
          "template/src/styles/palette.css"
        ];
      };

      settings.global = {
        excludes = [
          # Generated / vendored
          ".git/*"
          "fixtures/haskell-haddock/*"
          "fixtures/lean-theory/*"
          "nix/format/package-lock.json"
          "nix/materialized/*"
          "result*/*"
          "template/node_modules/*"
          "template/package-lock.json"
          # Static assets the consumer can override; never our
          # source of truth for whitespace.
          "template/public/*"
          # Generated by Astro's build pipeline.
          "template/src/generated/*"
          "template/result/*"
        ];
      };
    };

    # `nix fmt` entry point.
    formatter = config.treefmt.build.wrapper;

    # Surface the toolchain bundle so other modules (devshells, CI
    # apps) can reach it without re-deriving the package.
    legacyPackages._format-tools = formatTools;
  };
}
